# -*- coding: utf-8 -*-
"""angletoradian.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPBPQBwePLAHSnO5ngz8grQPV4eydBof
"""

import math
angle=float(input("enter an angle in degrees:"))
radian=math.radians(angle)
print("sine of angle",math.sin(radian))
print("cosine of angle", math.cos(radian))
print("tangent of angle",math.tan(radian))