# -*- coding: utf-8 -*-
"""datastructures.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M7a9n01hHdkU7pSGreUIu7akNFmm3_bI

**LISTS**
"""

years = [ 2002,2003,3004,3005]
years
years[2]

years[3]=2006
years

years.append(2007)
years

years.insert(2,1001)
years

years.pop(2)
years

years.remove(2006)
years

years.sort()
years

len(years)
years

years.reverse()
years

"""iterating through a list"""

for year in years:
    print(year)

"""TUPLES"""

size=(200,300,400)
size

print(size[2])

"""DICTIONARY"""

book={
    "name"   : "the predator",
    "author" : "runyx",
    "price"  : "1000"
    }
book

book
book["name"]

book
book["price"]=2000
print(book)

book["no. of pages"]=200
print(book)

del book["no. of pages"]
print(book)

for i , j in book.items():
  print(i,j)

"""SETS"""

numbers = {1,2,3,4,5}
numbers

numbers.add(6)
numbers

numbers.remove(4)
numbers

"""SET OPERATIONS"""

a={1,2,3,4,5}
b={4,5,6,7,8}
a|b

a&b

a-b