# -*- coding: utf-8 -*-
"""gradingsystem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KLLOiQj_ZEF2W1U6YJtpZsd051Otwk7b
"""

#grading system
a=int(input("the value of a is"))
if a>=90:
  print("A grade")
elif a>75:
  print("B grade")
elif a>50:
  print("c grade")
else:
  print("fail")