# -*- coding: utf-8 -*-
"""oops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4-oFCOmDbG--gCpeKfEG9Jfgi-TAVBI
"""

class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age
  def greet(self):
    print(f"Hello, my name is {self.name} and I am {self.age} years old.")
person1 = Person("virat", 36)
person1.greet()