# -*- coding: utf-8 -*-
"""typesofwaystoprint.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YPBPQBwePLAHSnO5ngz8grQPV4eydBof
"""

a=18
b=17
c= 1
print(f"virat's jersey number is {a}")
print("devillier's jersey number is",+b)
print(c)